### ISSUE TITLE
Drag up and down or left and right

### ISSUE THREAD

**Issue by vietnux** [Richard1320/jQuery-Circle-Menu#1]
Only rotate for Drag up and down or left and right?

**Comment by Richard1320** [comment]
You can choose horizontal or vertical with the `dragDirection` option, which takes `vertical` or `horizontal` as values.

**Comment by vietnux** [comment]
@Richard1320  not auto

**Comment by Richard1320** [comment]
No. It currently does not rotate automatically.

**Comment by vietnux** [comment]
you can save code to line 176

`//fix horizontal|vertically;
            var disX = x-mouse.x;
            var disY = y-mouse.y;
            if (Math.abs(disX) > Math.abs(disY)){ // if distance traveled horizontally is greater than vertically, consider this a horizontal movement
                settings.dragDirection = 'horizontal'
            } else{ // else consider this a vertical movement
                settings.dragDirection = 'vertically'
            }`

**Comment by Richard1320** [comment]
I chose not to add add automatic direction for usability reasons, not because of technical limitations. Dragging from the bottom left to top right would cancel out and going from top left to bottom right would double the movement. Thanks for trying to help.

**Comment by vietnux** [comment]
không có gì
